GET http://localhost:8889/categories

### 
GET http://localhost:8889/categories/20da71d8-48b2-4818-9cf6-c35b8b605ae4

###
POST http://localhost:8889/categories
Content-Type: application/json

{
    "name": "Test"
}

###
DELETE http://localhost:8889/categories/4c66a7a5-0f67-41f0-86be-804ca37f8535

###
PUT http://localhost:8889/categories/8f86edac-45c14e3c-b0df-46b6bcada092
Content-Type: application/json

{
    "name": "Movie"
}

