GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/bbc82606-6bf3-4713-8b5a-f3d89eaaf84e

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Horror"
}

###
PUT http://localhost:3000/categories/bbc82606-6bf3-4713-8b5a-f3d89eaaf84e
Content-Type: application/json

{
    "name": "Movie111111"
}

###
DELETE  http://localhost:3000/categories/bbc82606-6bf3-4713-8b5a-f3d89eaaf84e
Content-Type: application/json